In [10]:
import pandas as pd

caminho_arquivo = "data/Resultados_Mercado.xlsx"

xls = pd.ExcelFile(caminho_arquivo)
print("Abas da planilha:")
print(xls.sheet_names)

Abas da planilha:
['Perfil', 'Usuário', 'Faixa Etária', 'Identificação de Perfil', 'Região', 'Para Lojas', 'AdministradorGerente', 'ClubesAssociados', 'CargoClube', 'Comercialização', 'Frequência de Tiro', 'Nível Técnico', 'QntdProjéteis', 'Modalidade', 'PráticaFrequen.', 'Escolha Projéteis', 'Nível Técnico Calibre', 'Calibre Região', 'Avaliação', 'Ident.Perfil', 'NívelTecnico', 'Amostra Gestão Clube', 'Qntd.Resíduos', 'Reaproveitamento', 'Marcas', 'RegiõesMarcas', 'Modali.Projétil', 'Recom.Projéteis', 'Tipos Projéteis', 'TestarNovo', 'MotivaçãoNovo', 'Confia.Marcas', 'Confia.Perfil', 'Erros Mercado', 'Rede']

In [11]:
aba = "Identificação de Perfil"

df_teste = pd.read_excel(caminho_arquivo, sheet_name=aba, header=None)

print(f"Aba: {aba}")
display(df_teste.head(10))

Aba: Identificação de Perfil

,0,1,2,3,4
0,Identificação do Perfil,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,UF,Usuário Final,Gestor de Clube,Gestor de Loja de Armaria,Coluna1
3,Alagoas,0.5,0,0,0.25
4,Bahia,4.5,3,6,4.5
5,Ceará,2,4,0,2
6,Distrito Federal,3,6,2,3.5
7,Espírito Santo,3,2,0,2
8,Goiás,3,3,10,4.75
9,Mato Grosso,2,0,0,1

In [12]:
df_identificacao = pd.read_excel(
    caminho_arquivo,
    sheet_name="Identificação de Perfil",
    header=1   # ou 2, dependendo do que o preview mostrar
)

df_identificacao.columns = df_identificacao.columns.str.strip()
print(df_identificacao.columns.tolist())
display(df_identificacao.head())

['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,UF,Usuário Final,Gestor de Clube,Gestor de Loja de Armaria,Coluna1
1,Alagoas,0.5,0,0,0.25
2,Bahia,4.5,3,6,4.5
3,Ceará,2,4,0,2
4,Distrito Federal,3,6,2,3.5

In [13]:
df_identificacao = pd.read_excel(
    caminho_arquivo,
    sheet_name="Identificação de Perfil",
    header=2
)

In [14]:
df_identificacao.columns = df_identificacao.columns.str.strip()

# remove coluna inútil
df_identificacao = df_identificacao.loc[:, ~df_identificacao.columns.str.contains("^Unnamed")]

In [15]:
import pandas as pd

# 1. Caminho do arquivo Excel
caminho_arquivo = "data/Resultados_Mercado.xlsx"

try:
    # 2. Ler a aba correta com o cabeçalho real
    df_identificacao = pd.read_excel(
        caminho_arquivo,
        sheet_name="Identificação de Perfil",
        header=2
    )

    # 3. Limpar nomes das colunas
    df_identificacao.columns = (
        df_identificacao.columns.astype(str)
        .str.strip()
        .str.replace("\n", " ", regex=False)
    )

    # 4. Remover colunas vazias/inúteis tipo Unnamed
    df_identificacao = df_identificacao.loc[
        :, ~df_identificacao.columns.str.contains("^Unnamed")
    ]

    # 5. Mostrar as colunas para conferência
    print("Colunas identificadas:")
    print(df_identificacao.columns.tolist())

    # 6. Transformar de formato largo para formato longo
    df_identificacao_tratado = pd.melt(
        df_identificacao,
        id_vars=["UF"],
        var_name="Perfil",
        value_name="Porcentagem"
    )

    # 7. Arredondar valores
    df_identificacao_tratado["Porcentagem"] = (
        df_identificacao_tratado["Porcentagem"].round(2)
    )

    # 8. Visualizar resultado
    print("\n✅ Transformação concluída com sucesso!")
    display(df_identificacao_tratado.head(10))

    # 9. Salvar CSV limpo
    df_identificacao_tratado.to_csv(
        "identificacao_perfil_limpo.csv",
        index=False,
        sep=";",
        decimal=","
    )

    print("\n✅ Arquivo salvo como: identificacao_perfil_limpo.csv")

except Exception as e:
    print(f"❌ Ocorreu um erro: {e}")

Colunas identificadas:
['UF', 'Usuário Final', 'Gestor de Clube', 'Gestor de Loja de Armaria', 'Coluna1']

✅ Transformação concluída com sucesso!

                     UF         Perfil  Porcentagem
0               Alagoas  Usuário Final          0.5
1                 Bahia  Usuário Final          4.5
2                 Ceará  Usuário Final          2.0
3      Distrito Federal  Usuário Final          3.0
4        Espírito Santo  Usuário Final          3.0
5                 Goiás  Usuário Final          3.0
6           Mato Grosso  Usuário Final          2.0
7    Mato Grosso do Sul  Usuário Final          2.5
8          Minas Gerais  Usuário Final         10.5
9                  Pará  Usuário Final          0.0

✅ Arquivo salvo como: identificacao_perfil_limpo.csv

In [16]:
import pandas as pd

# 1. Caminho do arquivo
caminho_arquivo = "data/Resultados_Mercado.xlsx"

try:
    # 2. Ler a aba correta com o cabeçalho real
    df_identificacao = pd.read_excel(
        caminho_arquivo,
        sheet_name="Identificação de Perfil",
        header=2
    )

    print("✅ Base carregada com sucesso!")

    # 3. Limpar nomes das colunas
    df_identificacao.columns = (
        df_identificacao.columns.astype(str)
        .str.strip()
        .str.replace("\n", " ", regex=False)
    )

    # 4. Remover colunas inúteis/vazias
    df_identificacao = df_identificacao.loc[
        :, ~df_identificacao.columns.str.contains("^Unnamed", na=False)
    ]

    df_identificacao = df_identificacao.drop(columns=["Coluna1"], errors="ignore")

    # 5. Arredondar colunas numéricas
    colunas_numericas = [
        "Usuário Final",
        "Gestor de Clube",
        "Gestor de Loja de Armaria"
    ]

    for col in colunas_numericas:
        if col in df_identificacao.columns:
            df_identificacao[col] = pd.to_numeric(df_identificacao[col], errors="coerce").round(2)

    # 6. Visualizar
    print("\n✅ Dados tratados:")
    display(df_identificacao.head(10))

    # 7. Salvar CSV pronto para Power BI
    df_identificacao.to_csv(
        "identificacao_perfil_pronto.csv",
        index=False,
        sep=";",
        decimal=","
    )

    print("\n✅ Arquivo salvo como: identificacao_perfil_pronto.csv")

except Exception as e:
    print(f"❌ Ops! Ocorreu um erro: {e}")

✅ Base carregada com sucesso!

✅ Dados tratados:

,UF,Usuário Final,Gestor de Clube,Gestor de Loja de Armaria
0,Alagoas,0.5,0,0.0
1,Bahia,4.5,3,6.0
2,Ceará,2.0,4,0.0
3,Distrito Federal,3.0,6,2.0
4,Espírito Santo,3.0,2,0.0
5,Goiás,3.0,3,10.0
6,Mato Grosso,2.0,0,0.0
7,Mato Grosso do Sul,2.5,0,2.0
8,Minas Gerais,10.5,18,12.0
9,Pará,0.0,2,0.0

✅ Arquivo salvo como: identificacao_perfil_pronto.csv

In [17]:
import os
import pandas as pd

caminho_arquivo = "data/Resultados_Mercado.xlsx"
pasta_saida = "outputs"

os.makedirs(pasta_saida, exist_ok=True)

try:
    
    #1. PERFIL (GÊNERO)
   
    df_perfil = pd.read_excel(
        caminho_arquivo,
        sheet_name="Perfil",
        header=0
    )

    df_perfil.columns = df_perfil.columns.str.strip()

    df_perfil = df_perfil.rename(columns={
        "Porcentagem (%)": "Porcentagem"
    })

    df_perfil["Porcentagem"] = pd.to_numeric(
        df_perfil["Porcentagem"], errors="coerce"
    ).round(2)

    df_perfil.to_csv(
        os.path.join(pasta_saida, "perfil_limpo.csv"),
        index=False,
        sep=";",
        decimal=","
    )

    print("✅ Perfil salvo")

   
    #2. USUÁRIO
  
    df_usuario = pd.read_excel(
        caminho_arquivo,
        sheet_name="Usuário",
        header=0
    )

    df_usuario.columns = df_usuario.columns.str.strip()

    df_usuario = df_usuario.rename(columns={
        "Porcentagem (%)": "Porcentagem"
    })

    df_usuario["Porcentagem"] = pd.to_numeric(
        df_usuario["Porcentagem"], errors="coerce"
    ).round(2)

    df_usuario.to_csv(
        os.path.join(pasta_saida, "usuario_limpo.csv"),
        index=False,
        sep=";",
        decimal=","
    )

    print("✅ Usuário salvo")

    print("\n🚀 Tudo processado com sucesso!")

except Exception as e:
    print(f"❌ Erro: {e}")

✅ Perfil salvo
✅ Usuário salvo

🚀 Tudo processado com sucesso!

In [18]:
import pandas as pd

caminho_arquivo = "data/Resultados_Mercado.xlsx"

df_perfil = pd.read_excel(caminho_arquivo, sheet_name="Perfil", header=None)
display(df_perfil.head(8))

df_usuario = pd.read_excel(caminho_arquivo, sheet_name="Usuário", header=None)
display(df_usuario.head(8))

             0                1
0       Gênero  Porcentagem (%)
1     Feminino             7.25
2    Masculino            92.75

                             0                1
0               Usuário Final   Porcentagem (%)
1              Gestor de clube               25
2    Gestor de loja de armaria               25

In [19]:
import pandas as pd

caminho_arquivo = "data/Resultados_Mercado.xlsx"

xls = pd.ExcelFile(caminho_arquivo)

print("Abas disponíveis:")
print(xls.sheet_names)

for aba in xls.sheet_names:
    print(f"\n=== {aba} ===")
    df = pd.read_excel(caminho_arquivo, sheet_name=aba, header=None)
    display(df.head(6))

Abas disponíveis:
['Perfil', 'Usuário', 'Faixa Etária', 'Identificação de Perfil', 'Região', 'Para Lojas', 'AdministradorGerente', 'ClubesAssociados', 'CargoClube', 'Comercialização', 'Frequência de Tiro', 'Nível Técnico', 'QntdProjéteis', 'Modalidade', 'PráticaFrequen.', 'Escolha Projéteis', 'Nível Técnico Calibre', 'Calibre Região', 'Avaliação', 'Ident.Perfil', 'NívelTecnico', 'Amostra Gestão Clube', 'Qntd.Resíduos', 'Reaproveitamento', 'Marcas', 'RegiõesMarcas', 'Modali.Projétil', 'Recom.Projéteis', 'Tipos Projéteis', 'TestarNovo', 'MotivaçãoNovo', 'Confia.Marcas', 'Confia.Perfil', 'Erros Mercado', 'Rede']

=== Perfil ===

             0                1
0       Gênero  Porcentagem (%)
1     Feminino             7.25
2    Masculino            92.75

=== Usuário ===

                             0                1
0               Usuário Final   Porcentagem (%)
1              Gestor de clube               25
2    Gestor de loja de armaria               25

=== Faixa Etária ===

                    0                1
0        Faixa Etária  Porcentagem (%)
1        26 a 34 anos             19.5
2        35 a 44 anos             30.5
3        45 a 59 anos               42
4    Acima de 60 anos             6.25
5         Até 25 anos             1.75

=== Identificação de Perfil ===

,0,1,2,3,4
0,Identificação do Perfil,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,UF,Usuário Final,Gestor de Clube,Gestor de Loja de Armaria,Coluna1
3,Alagoas,0.5,0,0,0.25
4,Bahia,4.5,3,6,4.5
5,Ceará,2,4,0,2

=== Região ===

                0                1
0         Região   Porcentagem (%)
1         Sudeste            50.25
2             Sul            25.25
3        Nordeste               11
4    Centro-Oeste               11
5           Norte              2.5

=== Para Lojas ===

                        0                1
0                   Lojas  Porcentagem (%)
1      Até 5 funcionários               92
2     6 a 15 funcionários                6
3    16 a 50 funcionários                2

=== AdministradorGerente ===

                           0                1
0                      Lojas  Porcentagem (%)
1    Administrador / Gerente        44.318182
2       Proprietário / Sócio        55.681818

=== ClubesAssociados ===

                                   0                1
0  Quantidade de Associados no Clube  Porcentagem (%)
1                            Até 199               17
2                          200 a 499               26
3                          500 a 999               19
4                     Acima de 1.000               30
5                       Não informou                8

=== CargoClube ===

                                0                1
0   Cargo Correnpondente no Clube  Porcentagem (%)
1        Gerente / Administrativo               19
2          Instrutor / Secretário               12
3    Presidente / Diretor / Sócio               69

=== Comercialização ===

                                                   0          1          2
0  O clube comercializa projéteis ou munições dir...        NaN        NaN
1                                                NaN        NaN        NaN
2                                             Região        Sim        Não
3                                            Sudeste  44.680851  55.319149
4                                                Sul         75         25
5                                           Nordeste  30.769231  69.230769

=== Frequência de Tiro ===

                         0                1
0            Usuário Final  Porcentagem (%)
1    Mais de 2x por semana             20.5
2            1x por semana             26.5
3                Quinzenal                9
4                   Mensal               27
5                 Eventual               17

=== Nível Técnico ===

                                  0                1
0    Nível Técnico - Usuário Final   Porcentagem (%)
1    Competitivo / alta performance              4.5
2                          Avançado             24.5
3                     Intermediário               47
4                         Iniciante               24

=== QntdProjéteis ===

                                                   0                1
0  Em média, quantos projéteis você utiliza/compr...              NaN
1                                                NaN              NaN
2                            Quantidade de Projéteis  Porcentagem (%)
3                              Até 200 projéteis/mês             23.5
4                                          201 a 500               14
5                                      1.001 a 2.000             15.5

=== Modalidade ===

                                                   0                1
0  Quais modalidades você pratica ou atende com m...              NaN
1                                                NaN              NaN
2                                         Modalidade  Porcentagem (%)
3                         Tiro esportivo de precisão             70.5
4                           Treinamento / recreativo               64
5                                    IPSC / dinâmico            34.75

=== PráticaFrequen. ===

,0,1,2,3,4,5,6,7,8
0,Quais modalidades você pratica ou atende com m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,Região,NaN,NaN,NaN,NaN
3,Modalidade,Usuário Final,Gestor de Clube,Gestor de Loja de Armaria,Sudeste,Sul,Nordeste,Centro - Oeste,Norte
4,Air Soft,0,0,100,0,100,0,0,0
5,Tiro esportivo de precisão,45.035461,26.950355,28.014184,53.546099,25.531915,8.510638,10.283688,2.12766

=== Escolha Projéteis ===

                                                   0                1
0  _x000D_\nQuais calibres você utiliza / vende /...              NaN
1                                                NaN              NaN
2                                            Calibre  Porcentagem (%)
3                                        Calibre 9mm        70.955882
4                                        Calibre 380        59.191176
5                                         Calibre 38        57.720588

=== Nível Técnico Calibre ===

,0,1,2,3,4
0,COMO VOCÊ AVALIA O SEU NÍVEL TÉCNICO?,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,Calibre,Competitivo/Alta Performace,Avançado,Intermediário,Iniciante
3,Calibre 40,0,33.333333,66.666667,0
4,Calibre 45,0,0,100,0
5,Calibre 12,33.333333,22.222222,44.444444,0

=== Calibre Região ===

,0,1,2,3,4,5
0,Calibre,Sudeste (%),Sul (%),Nordeste (%),Centro - Oeste (%),Norte (%)
1,Calibre 9mm,67.424242,71.428571,74.193548,78.125,85.714286
2,Calibre 380,62.121212,52.857143,58.064516,56.25,85.714286
3,Calibre 38,64.393939,62.857143,38.709677,40.625,42.857143
4,Calibre 22,28.787879,37.142857,19.354839,34.375,0
5,Calibre 40,15.909091,22.857143,19.354839,18.75,0

=== Avaliação ===

,0,1,2,3,4,5
0,Avalie a importância de cada fator na escolha ...,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,Fator,Portecentagem (%),Portecentagem (%)2,Portecentagem (%)3,Portecentagem (%)4,Portecentagem (%)5
3,Precisão e desempenho balístico,3.985507,1.449275,10.869565,21.014493,62.681159
4,Tipo de material e acabament,3.26087,2.173913,29.710145,34.782609,30.072464
5,Compatibilidade com sua arma e modalidade,3.26087,1.449275,3.26087,19.202899,72.826087

=== Ident.Perfil ===

,0,1,2,3
0,Nota Média,Usuário Final,Getsor de Clube,Gestor de Loja de Armaria
1,Precisão e desempenho balístico,4.39,4.444444,4.2
2,Tipo de material e acabament,3.765,4.111111,4.125
3,Compatibilidade com sua arma e modalidade,4.63,4.277778,4.525
4,Custo por disparo,3.95,4.416667,3.7
5,Marca / reputação do fabricante,4.055,3.666667,3.825

=== NívelTecnico ===

                                       0         1              2          3
0  Como você avalia o seu nível técnico?       NaN            NaN        NaN
1                                    NaN       NaN            NaN        NaN
2          Competitivo / Alta Performace  Avançado  Intermediário  Iniciante
3                               3.888889  4.510204       4.404255   4.333333
4                               3.222222  3.408163       4.053191   3.666667
5                               4.111111  4.755102       4.680851        4.5

=== Amostra Gestão Clube ===

                                                   0                1
0  Após os disparos, o que é feito com os resíduo...  Porcentagem (%)
1                       Não existe processo definido               80
2                                Recarga de munições                6
3                              Venda para reciclagem                6
4                                   Revende o chumbo                5
5                       Doação para empresa / pessoa                2

=== Qntd.Resíduos ===

                                                   0                1
0  Você teria uma estimativa da quantidade de res...              NaN
1                                                NaN              NaN
2                                         Estimativa  Porcentagem (%)
3                                   Até 50kg por mês               17
4                            De 51kg a 200kg por mês                6
5                           De 201kg a 500kg por mês                2

=== Reaproveitamento ===

,0,1,2,3
0,O clube teria interesse em soluções mais estru...,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,Região,Não,Sim,Talvez
4,Sudeste,80.851064,14.893617,4.255319
5,Sul,58.333333,20.833333,20.833333

=== Marcas ===

                                                   0                1
0  Quais marcas de projéteis você utiliza ou reco...              NaN
1                                                NaN              NaN
2                                             Marcas  Porcentagem (%)
3                                                CBC            57.25
4                                   NÃO SABE A MARCA               14
5                                             MORIGI            13.75

=== RegiõesMarcas ===

,0,1,2,3,4,5
0,Quais marcas de projéteis você utiliza ou reco...,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,Marcas,Sudeste,Sul,Nordeste,Centro - Oeste,Norte
3,CBC,60.199005,50.49505,59.090909,54.545455,70
4,NÃO SABE A MARCA,14.427861,16.831683,9.090909,11.363636,10
5,MORIGI,16.41791,9.90099,9.090909,13.636364,20

=== Modali.Projétil ===

                                                  0                1
0                     Motivo de utilizar o projétil  Porcentagem (%)
1                              Qualidade/Desempenho             32.5
2                             Preço/Custo-Benefício             25.5
3                        Confiança/Costume/Parceria             23.5
4    Disponibilidade/Logística/Facilidade de compra               23
5                         Disponibilidade/Logística            11.25

=== Recom.Projéteis ===

,0,1,2,3,4,5,6
0,QUAIS MARCAS DE PROJÉTEIS VOCÊ UTILIZA OU RECO...,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Motivo,BULLETS (%),CBC (%),MORIGI (%),MARCONDES (%),LYON (%),BUFALO (%)
3,Qualidade/Desempenho,0,24.89083,60,51.724138,63.333333,52.631579
4,Confiança/Costume/Parceria,0,22.270742,30.909091,41.37931,26.666667,36.842105
5,Preço/Custo-Benefício,0,27.947598,27.272727,24.137931,6.666667,18.421053

=== Tipos Projéteis ===

                                                   0                1
0  Qual tipo de projétil que hoje você sente falt...              NaN
1                                                NaN              NaN
2                                          Projéteis  Porcentagem (%)
3                                       Não informou             53.5
4                                               .308                3
5                                         IMPORTADOS                3

=== TestarNovo ===

                                                   0                1
0   Em quais condições você consideraria testar u...              NaN
1                                                NaN              NaN
2                                           Condição  Porcentagem (%)
3                  Se o preço fosse mais competitivo               45
4                                   Amostra gratuita            39.75
5                     Após testes práticos em treino             36.5

=== MotivaçãoNovo ===

                                                   0                1
0  O que mais lhe motivaria a testar um novo proj...              NaN
1                                                NaN              NaN
2                                           Condição  Porcentagem (%)
3                                 Amostras gratuitas            52.25
4                                  Preço promocional               44
5                                Testes comparativos               37

=== Confia.Marcas ===

                                                   0                1
0  Que argumentos uma nova marca de projéteis pre...              NaN
1                                                NaN              NaN
2                                          Argumento  Porcentagem (%)
3                     Acabamento/Preservação Da Arma                6
4     Algum diferencial em relação à marca utilizada              0.5
5                  Baixa emissão de gases e resíduos             0.25

=== Confia.Perfil ===

,0,1,2,3
0,Que argumentos uma nova marca de projéteis pre...,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,Argumento,Usuário Final (%),Gestor de Clube (%),Gestor de Loja de Armaria (%)
3,Confiança / Segurança no disparo,47,41,43
4,Preço/Custo-Benefício,35,36,37
5,Precisão || Desempenho do disparo,24,32,17

=== Erros Mercado ===

                                                   0                1
0  Na sua opinião, quais erros marcas novas costu...              NaN
1                                                NaN              NaN
2                                             Motivo  Porcentagem (%)
3  Qualidade/Falta padronização peso / pintura / ...             31.8
4  Falta divulgação e marketing das vantagens do ...               22
5                                           Não sabe               15

=== Rede ===

                                                   0                1
0  Onde você busca informação confiável sobre pro...              NaN
1                                                NaN              NaN
2                                              Canal  Porcentagem (%)
3                             Internet/Midia/Digital             42.5
4                                  Atiradores/Amigos               35
5                     Autoridade/Instrutores/Atletas            24.75

In [20]:
import os
import pandas as pd


# 1. CONFIGURAÇÃO

caminho_arquivo = "data/Resultados_Mercado.xlsx"
pasta_saida = "outputs"

os.makedirs(pasta_saida, exist_ok=True)


# 2. FUNÇÕES AUXILIARES

def limpar_colunas(df):
    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.replace("\n", " ", regex=False)
    )
    df = df.loc[:, ~df.columns.str.contains("^Unnamed", na=False)]
    df = df.drop(columns=["Coluna1"], errors="ignore")
    return df

def arredondar_numericas(df):
    for col in df.columns[1:]:
        serie_convertida = pd.to_numeric(df[col], errors="coerce")
        if serie_convertida.notna().any():
            df[col] = serie_convertida.round(2)
    return df

def salvar_csv(df, nome_arquivo):
    df.to_csv(
        os.path.join(pasta_saida, nome_arquivo),
        index=False,
        sep=";",
        decimal=","
    )

def tratar_aba_simples(sheet_name, nome_csv, header=0):
    df = pd.read_excel(caminho_arquivo, sheet_name=sheet_name, header=header)
    df = limpar_colunas(df)
    df = arredondar_numericas(df)

    if len(df.columns) == 2:
        df.columns = [df.columns[0], "Porcentagem"]
        df["Porcentagem"] = pd.to_numeric(df["Porcentagem"], errors="coerce").round(2)

    salvar_csv(df, nome_csv)
    print(f"✅ {sheet_name} tratado e salvo em {nome_csv}")
    display(df.head(10))
    return df

def tratar_aba_matriz(sheet_name, nome_csv, id_var, header=2, var_name="Categoria", value_name="Porcentagem"):
    df = pd.read_excel(caminho_arquivo, sheet_name=sheet_name, header=header)
    df = limpar_colunas(df)

    df_longo = pd.melt(
        df,
        id_vars=[id_var],
        var_name=var_name,
        value_name=value_name
    )

    df_longo[value_name] = pd.to_numeric(df_longo[value_name], errors="coerce").round(2)

    salvar_csv(df_longo, nome_csv)
    print(f"✅ {sheet_name} tratado e salvo em {nome_csv}")
    display(df_longo.head(10))
    return df_longo


# 3. PERFIL E DINÂMICA DE USO

try:
    print("\n=== PERFIL ===")
    df_perfil = tratar_aba_simples("Perfil", "perfil_limpo.csv", header=0)

    print("\n=== USUÁRIO ===")
    df_usuario = tratar_aba_simples("Usuário", "usuario_limpo.csv", header=0)

    print("\n=== FAIXA ETÁRIA ===")
    df_faixa = tratar_aba_simples("Faixa Etária", "faixa_etaria_limpo.csv", header=0)

    print("\n=== IDENTIFICAÇÃO DE PERFIL ===")
    df_identificacao = tratar_aba_matriz(
        "Identificação de Perfil",
        "identificacao_perfil_limpo.csv",
        id_var="UF",
        header=2,
        var_name="Perfil",
        value_name="Porcentagem"
    )

    print("\n=== REGIÃO ===")
    df_regiao = tratar_aba_simples("Região", "regiao_limpo.csv", header=0)

    print("\n=== FREQUÊNCIA DE TIRO ===")
    df_freq = tratar_aba_simples("Frequência de Tiro", "frequencia_tiro_limpo.csv", header=0)

    print("\n=== NÍVEL TÉCNICO ===")
    df_nivel = tratar_aba_simples("Nível Técnico", "nivel_tecnico_limpo.csv", header=0)

    print("\n=== QNTDPROJÉTEIS ===")
    df_qtd = tratar_aba_simples("QntdProjéteis", "qntd_projeteis_limpo.csv", header=2)

    print("\n=== MODALIDADE ===")
    df_modalidade = tratar_aba_simples("Modalidade", "modalidade_limpo.csv", header=0)

    print("\n🚀 BLOCO 'PERFIL E DINÂMICA DE USO' PROCESSADO COM SUCESSO!")

except Exception as e:
    print(f"❌ Erro no processamento: {e}")

=== PERFIL ===
✅ Perfil tratado e salvo em perfil_limpo.csv

        Gênero  Porcentagem
0     Feminino         7.25
1    Masculino        92.75

=== USUÁRIO ===
✅ Usuário tratado e salvo em usuario_limpo.csv

                 Usuário Final  Porcentagem
0              Gestor de clube           25
1    Gestor de loja de armaria           25

=== FAIXA ETÁRIA ===
✅ Faixa Etária tratado e salvo em faixa_etaria_limpo.csv

         Faixa Etária  Porcentagem
0        26 a 34 anos        19.50
1        35 a 44 anos        30.50
2        45 a 59 anos        42.00
3    Acima de 60 anos         6.25
4         Até 25 anos         1.75

=== IDENTIFICAÇÃO DE PERFIL ===
✅ Identificação de Perfil tratado e salvo em identificacao_perfil_limpo.csv

                     UF         Perfil  Porcentagem
0               Alagoas  Usuário Final          0.5
1                 Bahia  Usuário Final          4.5
2                 Ceará  Usuário Final          2.0
3      Distrito Federal  Usuário Final          3.0
4        Espírito Santo  Usuário Final          3.0
5                 Goiás  Usuário Final          3.0
6           Mato Grosso  Usuário Final          2.0
7    Mato Grosso do Sul  Usuário Final          2.5
8          Minas Gerais  Usuário Final         10.5
9                  Pará  Usuário Final          0.0

=== REGIÃO ===
✅ Região tratado e salvo em regiao_limpo.csv

           Região  Porcentagem
0         Sudeste        50.25
1             Sul        25.25
2        Nordeste        11.00
3    Centro-Oeste        11.00
4           Norte         2.50

=== FREQUÊNCIA DE TIRO ===
✅ Frequência de Tiro tratado e salvo em frequencia_tiro_limpo.csv

             Usuário Final  Porcentagem
0    Mais de 2x por semana         20.5
1            1x por semana         26.5
2                Quinzenal          9.0
3                   Mensal         27.0
4                 Eventual         17.0

=== NÍVEL TÉCNICO ===
✅ Nível Técnico tratado e salvo em nivel_tecnico_limpo.csv

      Nível Técnico - Usuário Final  Porcentagem
0    Competitivo / alta performance          4.5
1                          Avançado         24.5
2                     Intermediário         47.0
3                         Iniciante         24.0

=== QNTDPROJÉTEIS ===
✅ QntdProjéteis tratado e salvo em qntd_projeteis_limpo.csv

                             Quantidade de Projéteis  Porcentagem
0                              Até 200 projéteis/mês         23.5
1                                          201 a 500         14.0
2                                      1.001 a 2.000         15.5
3                                      2.001 a 5.000          1.0
4                                     Acima de 5.000         26.0
5    Não compro projéteis (uso apenas munição pro...         14.0
6                             Não sabe / varia muito          6.0

=== MODALIDADE ===
✅ Modalidade tratado e salvo em modalidade_limpo.csv

  Quais modalidades você pratica ou atende com maior frequência?
0                                                NaN
1                                         Modalidade
2                         Tiro esportivo de precisão
3                           Treinamento / recreativo
4                                    IPSC / dinâmico
5                  Treinamento tático / profissional
6                                         Competição
7                                       Não informou
8                                           Air Soft
9                               Tiro ao Prato (TRAP)

🚀 BLOCO 'PERFIL E DINÂMICA DE USO' PROCESSADO COM SUCESSO!

In [21]:
import os
import pandas as pd


# 1. CONFIGURAÇÃO

caminho_arquivo = "data/Resultados_Mercado.xlsx"
pasta_saida = "outputs"

os.makedirs(pasta_saida, exist_ok=True)


# 2. FUNÇÕES AUXILIARES

def limpar_colunas(df):
    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.replace("\n", " ", regex=False)
    )
    df = df.loc[:, ~df.columns.str.contains("^Unnamed", na=False)]
    df = df.drop(columns=["Coluna1"], errors="ignore")
    return df

def salvar_csv(df, nome_arquivo):
    df.to_csv(
        os.path.join(pasta_saida, nome_arquivo),
        index=False,
        sep=";",
        decimal=","
    )

def arredondar_numericas(df):
    for col in df.columns[1:]:
        serie = pd.to_numeric(df[col], errors="coerce")
        if serie.notna().any():
            df[col] = serie.round(2)
    return df


# 3. ESCOLHA PROJÉTEIS

try:
    # ---------------------------------
    # A) ESCOLHA PROJÉTEIS
    # ---------------------------------
    print("\n=== ESCOLHA PROJÉTEIS ===")
    df_escolha_proj = pd.read_excel(
        caminho_arquivo,
        sheet_name="Escolha Projéteis",
        header=2
    )

    df_escolha_proj = limpar_colunas(df_escolha_proj)
    df_escolha_proj.columns = ["Calibre", "Porcentagem"]
    df_escolha_proj["Porcentagem"] = pd.to_numeric(df_escolha_proj["Porcentagem"], errors="coerce").round(2)

    salvar_csv(df_escolha_proj, "escolha_projeteis_limpo.csv")
    print("✅ Escolha Projéteis salvo")
    display(df_escolha_proj)


    # B) NÍVEL TÉCNICO CALIBRE
  
    print("\n=== NÍVEL TÉCNICO CALIBRE ===")
    df_nivel_calibre = pd.read_excel(
        caminho_arquivo,
        sheet_name="Nível Técnico Calibre",
        header=2
    )

    df_nivel_calibre = limpar_colunas(df_nivel_calibre)
    df_nivel_calibre = arredondar_numericas(df_nivel_calibre)

    salvar_csv(df_nivel_calibre, "nivel_tecnico_calibre_limpo.csv")
    print("✅ Nível Técnico Calibre salvo")
    display(df_nivel_calibre)

  
    # C) CALIBRE REGIÃO
    
    print("\n=== CALIBRE REGIÃO ===")
    df_calibre_regiao = pd.read_excel(
        caminho_arquivo,
        sheet_name="Calibre Região",
        header=0
    )

    df_calibre_regiao = limpar_colunas(df_calibre_regiao)
    df_calibre_regiao = arredondar_numericas(df_calibre_regiao)

    salvar_csv(df_calibre_regiao, "calibre_regiao_limpo.csv")
    print("✅ Calibre Região salvo")
    display(df_calibre_regiao)

  
    # D) AVALIAÇÃO
  
    df_avaliacao = pd.read_excel(
        caminho_arquivo,
        sheet_name="Avaliação",
        header=2
    )

    df_avaliacao = limpar_colunas(df_avaliacao)

    # renomear colunas de nota
    df_avaliacao.columns = [
        "Fator",
        "Nota_1",
        "Nota_2",
        "Nota_3",
        "Nota_4",
        "Nota_5"
    ]

    df_avaliacao["Fator"] = df_avaliacao["Fator"].astype(str).str.strip()

    for col in ["Nota_1", "Nota_2", "Nota_3", "Nota_4", "Nota_5"]:
        df_avaliacao[col] = pd.to_numeric(df_avaliacao[col], errors="coerce").round(2)

    salvar_csv(df_avaliacao, "avaliacao_escolha_projetil_limpo.csv")
    print("✅ Avaliação salva")
    display(df_avaliacao)

    
    # E) IDENT.PERFIL
  
    print("\n=== IDENT.PERFIL ===")
    df_ident_perfil = pd.read_excel(
        caminho_arquivo,
        sheet_name="Ident.Perfil",
        header=0
    )

    df_ident_perfil = limpar_colunas(df_ident_perfil)
    df_ident_perfil.columns = [
        "Fator",
        "Usuario_Final",
        "Gestor_Clube",
        "Gestor_Loja_Armaria"
    ]

    df_ident_perfil["Fator"] = df_ident_perfil["Fator"].astype(str).str.strip()

    for col in ["Usuario_Final", "Gestor_Clube", "Gestor_Loja_Armaria"]:
        df_ident_perfil[col] = pd.to_numeric(df_ident_perfil[col], errors="coerce").round(2)

    salvar_csv(df_ident_perfil, "avaliacao_por_perfil_limpo.csv")
    print("✅ Ident.Perfil salvo")
    display(df_ident_perfil)

  
    # F) NÍVELTECNICO
    
    df_nivel_tecnico = pd.read_excel(
        caminho_arquivo,
        sheet_name="NívelTecnico",
        header=2
    )

    df_nivel_tecnico = limpar_colunas(df_nivel_tecnico)

    # a aba veio sem coluna de fator; reconstruir usando a ordem do Ident.Perfil
    fatores = df_ident_perfil["Fator"].tolist()

    # limitar ao número de fatores
    df_nivel_tecnico = df_nivel_tecnico.iloc[:len(fatores), :]

    # inserir coluna Fator
    df_nivel_tecnico.insert(0, "Fator", fatores)

    # renomear colunas
    df_nivel_tecnico.columns = [
        "Fator",
        "Competitivo_Alta_Performance",
        "Avancado",
        "Intermediario",
        "Iniciante"
    ]

    for col in ["Competitivo_Alta_Performance", "Avancado", "Intermediario", "Iniciante"]:
        df_nivel_tecnico[col] = pd.to_numeric(df_nivel_tecnico[col], errors="coerce").round(2)

    salvar_csv(df_nivel_tecnico, "avaliacao_por_nivel_tecnico_limpo.csv")
    print("✅ NívelTecnico salvo")
    display(df_nivel_tecnico)

    print("\n🚀 BLOCO 'ESCOLHA DO PROJÉTIL' PROCESSADO COM SUCESSO!")

except Exception as e:
    print(f"❌ Erro no processamento: {e}")

=== ESCOLHA PROJÉTEIS ===
✅ Escolha Projéteis salvo

           Calibre  Porcentagem
0      Calibre 9mm        70.96
1      Calibre 380        59.19
2       Calibre 38        57.72
3       Calibre 22        29.78
4       Calibre 40        18.01
5       Calibre 12        12.13
6       Calibre 45        11.40
7      Calibre 357         9.93
8           Outros         2.94
9       Calibre 36         1.84
10      Calibre 28         1.10
11    Não informou         0.74

=== NÍVEL TÉCNICO CALIBRE ===
✅ Nível Técnico Calibre salvo

,Calibre,Competitivo/Alta Performace,Avançado,Intermediário,Iniciante
0,Calibre 40,0.00,33.33,66.67,0.00
1,Calibre 45,0.00,0.00,100.00,0.00
2,Calibre 12,33.33,22.22,44.44,0.00
3,Outros,0.00,0.00,0.00,100.00
4,Calibre 22,0.00,16.67,50.00,33.33
5,Calibre 28,0.00,0.00,0.00,0.00
6,Calibre 357,0.00,0.00,0.00,0.00
7,Calibre 36,0.00,0.00,0.00,0.00
8,Calibre 38,0.00,0.00,53.85,46.15
9,Calibre 380,0.00,9.52,90.48,0.00
10,Calibre 9mm,5.71,25.71,68.57,0.00
11,Não informou,0.00,0.00,0.00,0.00

=== CALIBRE REGIÃO ===
✅ Calibre Região salvo

,Calibre,Sudeste (%),Sul (%),Nordeste (%),Centro - Oeste (%),Norte (%)
0,Calibre 9mm,67.42,71.43,74.19,78.12,85.71
1,Calibre 380,62.12,52.86,58.06,56.25,85.71
2,Calibre 38,64.39,62.86,38.71,40.62,42.86
3,Calibre 22,28.79,37.14,19.35,34.38,0.00
4,Calibre 40,15.91,22.86,19.35,18.75,0.00
5,Calibre 12,11.36,11.43,6.45,25.00,0.00
6,Calibre 45,9.85,18.57,6.45,9.38,0.00
7,Calibre 357,9.85,8.57,0.00,25.00,0.00
8,Outros,3.03,2.86,0.00,6.25,0.00
9,Calibre 36,1.52,4.29,0.00,0.00,0.00
10,Calibre 28,0.00,4.29,0.00,0.00,0.00
11,Não informou,1.52,0.00,0.00,0.00,0.00

✅ Avaliação salva

,Fator,Nota_1,Nota_2,Nota_3,Nota_4,Nota_5
0,Precisão e desempenho balístico,3.99,1.45,10.87,21.01,62.68
1,Tipo de material e acabament,3.26,2.17,29.71,34.78,30.07
2,Compatibilidade com sua arma e modalidade,3.26,1.45,3.26,19.20,72.83
3,Custo por disparo,3.99,3.26,30.80,15.22,46.74
4,Marca / reputação do fabricante,3.99,3.99,25.72,23.55,42.75
5,Facilidade de aquisição – Disponibilidade no m...,6.16,7.97,8.33,19.20,58.33

=== IDENT.PERFIL ===
✅ Ident.Perfil salvo

,Fator,Usuario_Final,Gestor_Clube,Gestor_Loja_Armaria
0,Precisão e desempenho balístico,4.39,4.44,4.20
1,Tipo de material e acabament,3.76,4.11,4.12
2,Compatibilidade com sua arma e modalidade,4.63,4.28,4.53
3,Custo por disparo,3.95,4.42,3.70
4,Marca / reputação do fabricante,4.06,3.67,3.82
5,Facilidade de aquisição – Disponibilidade no m...,4.14,4.00,4.35

✅ NívelTecnico salvo

,Fator,Competitivo_Alta_Performance,Avancado,Intermediario,Iniciante
0,Precisão e desempenho balístico,3.89,4.51,4.40,4.33
1,Tipo de material e acabament,3.22,3.41,4.05,3.67
2,Compatibilidade com sua arma e modalidade,4.11,4.76,4.68,4.50
3,Custo por disparo,3.44,3.82,4.11,3.88
4,Marca / reputação do fabricante,4.11,4.10,4.18,3.75
5,Facilidade de aquisição – Disponibilidade no m...,3.44,4.47,4.10,4.04

🚀 BLOCO 'ESCOLHA DO PROJÉTIL' PROCESSADO COM SUCESSO!

In [22]:
import os
import pandas as pd


# 1. CONFIGURAÇÃO

caminho_arquivo = "data/Resultados_Mercado.xlsx"
pasta_saida = "outputs"

os.makedirs(pasta_saida, exist_ok=True)


# 2. FUNÇÕES AUXILIARES

def limpar_colunas(df):
    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.replace("\n", " ", regex=False)
    )
    df = df.loc[:, ~df.columns.str.contains("^Unnamed", na=False)]
    df = df.drop(columns=["Coluna1"], errors="ignore")
    return df

def salvar_csv(df, nome_arquivo):
    df.to_csv(
        os.path.join(pasta_saida, nome_arquivo),
        index=False,
        sep=";",
        decimal=","
    )

def arredondar_numericas(df):
    for col in df.columns[1:]:
        serie = pd.to_numeric(df[col], errors="coerce")
        if serie.notna().any():
            df[col] = serie.round(2)
    return df

def tratar_aba_simples(sheet_name, nome_csv, header=0):
    df = pd.read_excel(caminho_arquivo, sheet_name=sheet_name, header=header)
    df = limpar_colunas(df)
    df = arredondar_numericas(df)

    if len(df.columns) == 2:
        df.columns = [df.columns[0], "Porcentagem"]
        df["Porcentagem"] = pd.to_numeric(df["Porcentagem"], errors="coerce").round(2)

    salvar_csv(df, nome_csv)
    print(f"✅ {sheet_name} tratado e salvo em {nome_csv}")
    display(df.head(10))
    return df


# 3. RESÍDUOS E PÓS-USO

try:
    print("\n=== AMOSTRA GESTÃO CLUBE ===")
    df_amostra_clube = tratar_aba_simples(
        "Amostra Gestão Clube",
        "amostra_gestao_clube_limpo.csv",
        header=0
    )

    print("\n=== QNTD.RESÍDUOS ===")
    df_qtd_residuos = tratar_aba_simples(
        "Qntd.Resíduos",
        "qntd_residuos_limpo.csv",
        header=2
    )

    print("\n=== REAPROVEITAMENTO ===")
    df_reaproveitamento = tratar_aba_simples(
        "Reaproveitamento",
        "reaproveitamento_limpo.csv",
        header=3
    )

    print("\n🚀 BLOCO 'RESÍDUOS E PÓS-USO' PROCESSADO COM SUCESSO!")

except Exception as e:
    print(f"❌ Erro no processamento: {e}")

=== AMOSTRA GESTÃO CLUBE ===
✅ Amostra Gestão Clube tratado e salvo em amostra_gestao_clube_limpo.csv

  Após os disparos, o que é feito com os resíduos de projéteis?  Porcentagem
0                       Não existe processo definido                      80
1                                Recarga de munições                       6
2                              Venda para reciclagem                       6
3                                   Revende o chumbo                       5
4                       Doação para empresa / pessoa                       2
5                                Armazenado no local                       1

=== QNTD.RESÍDUOS ===
✅ Qntd.Resíduos tratado e salvo em qntd_residuos_limpo.csv

                        Estimativa  Porcentagem
0                 Até 50kg por mês           17
1          De 51kg a 200kg por mês            6
2         De 201kg a 500kg por mês            2
3    De 501kg a 1 tonelada por mês            0
4            Não possui estimativa           75

=== REAPROVEITAMENTO ===
✅ Reaproveitamento tratado e salvo em reaproveitamento_limpo.csv

           Região     Não    Sim  Talvez
0         Sudeste   80.85  14.89    4.26
1             Sul   58.33  20.83   20.83
2        Nordeste   84.62  15.38    0.00
3    Centro-Oeste   55.56  33.33   11.11
4           Norte  100.00   0.00    0.00

🚀 BLOCO 'RESÍDUOS E PÓS-USO' PROCESSADO COM SUCESSO!

In [23]:
import os
import pandas as pd


# CONFIGURAÇÃO

caminho_arquivo = "data/Resultados_Mercado.xlsx"
pasta_saida = "outputs"

os.makedirs(pasta_saida, exist_ok=True)


# FUNÇÕES AUXILIARES

def limpar_colunas(df):
    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.replace("\n", " ", regex=False)
    )
    df = df.loc[:, ~df.columns.str.contains("^Unnamed", na=False)]
    df = df.drop(columns=["Coluna1"], errors="ignore")
    return df

def salvar_csv(df, nome):
    df.to_csv(
        os.path.join(pasta_saida, nome),
        index=False,
        sep=";",
        decimal=","
    )

def arredondar(df):
    for col in df.columns[1:]:
        serie = pd.to_numeric(df[col], errors="coerce")
        if serie.notna().any():
            df[col] = serie.round(2)
    return df

def tratar_simples(sheet, nome_csv, header=0):
    df = pd.read_excel(caminho_arquivo, sheet_name=sheet, header=header)
    df = limpar_colunas(df)
    df = arredondar(df)

    if len(df.columns) == 2:
        df.columns = [df.columns[0], "Porcentagem"]
        df["Porcentagem"] = pd.to_numeric(df["Porcentagem"], errors="coerce").round(2)

    salvar_csv(df, nome_csv)
    print(f"✅ {sheet} OK")
    display(df.head(10))
    return df

def tratar_matriz(sheet, nome_csv, header=2):
    df = pd.read_excel(caminho_arquivo, sheet_name=sheet, header=header)
    df = limpar_colunas(df)

    # pega automaticamente a primeira coluna
    base = df.columns[0]

    print(f"Colunas em {sheet}:", df.columns.tolist())

    df_longo = pd.melt(
        df,
        id_vars=[base],
        var_name="Categoria",
        value_name="Porcentagem"
    )

    df_longo["Porcentagem"] = pd.to_numeric(
        df_longo["Porcentagem"],
        errors="coerce"
    ).round(2)

    salvar_csv(df_longo, nome_csv)
    print(f"✅ {sheet} OK (matriz)")
    display(df_longo.head(10))
    return df_longo


# BLOCO: MARCAS + NOVO PROJÉTIL

try:

    print("\n=== MARCAS ===")
    tratar_simples("Marcas", "marcas_limpo.csv", header=0)

    print("\n=== REGIÕESMARCAS ===")
    tratar_matriz("RegiõesMarcas", "regioes_marcas_limpo.csv", header=2)

    print("\n=== MODALI.PROJÉTIL ===")
    tratar_simples("Modali.Projétil", "modali_projetil_limpo.csv", header=0)

    print("\n=== RECOM.PROJÉTEIS ===")
    tratar_matriz("Recom.Projéteis", "recom_projeteis_limpo.csv", header=2)

    print("\n=== TIPOS PROJÉTEIS ===")
    tratar_simples("Tipos Projéteis", "tipos_projeteis_limpo.csv", header=0)

    print("\n=== TESTARNOVO ===")
    tratar_simples("TestarNovo", "testar_novo_limpo.csv", header=0)

    print("\n=== MOTIVAÇÃONOVO ===")
    tratar_simples("MotivaçãoNovo", "motivacao_novo_limpo.csv", header=0)

    print("\n=== CONFIA.MARCAS ===")
    tratar_simples("Confia.Marcas", "confia_marcas_limpo.csv", header=0)

    print("\n=== CONFIA.PERFIL ===")
    df_confia_perfil = pd.read_excel(
        caminho_arquivo,
        sheet_name="Confia.Perfil",
        header=2
    )

    df_confia_perfil = limpar_colunas(df_confia_perfil)
    df_confia_perfil = arredondar(df_confia_perfil)

    salvar_csv(df_confia_perfil, "confia_perfil_limpo.csv")
    print("✅ Confia.Perfil OK")
    display(df_confia_perfil.head(10))

    print("\n=== ERROS MERCADO ===")
    tratar_simples("Erros Mercado", "erros_mercado_limpo.csv", header=0)

    print("\n=== REDE ===")
    tratar_simples("Rede", "rede_limpo.csv", header=0)

    print("\n🚀 BLOCO FINAL PROCESSADO COM SUCESSO!")

except Exception as e:
    print(f"❌ Erro: {e}")

=== MARCAS ===
✅ Marcas OK

  Quais marcas de projéteis você utiliza ou recomenda atualmente?
0                                                NaN
1                                             Marcas
2                                                CBC
3                                   NÃO SABE A MARCA
4                                             MORIGI
5                                             Outros
6                                             BUFALO
7                                               LYON
8                                          MARCONDES
9                                              EAGLE

=== REGIÕESMARCAS ===
Colunas em RegiõesMarcas: ['Marcas', 'Sudeste', 'Sul', 'Nordeste', 'Centro - Oeste', 'Norte']
✅ RegiõesMarcas OK (matriz)

               Marcas Categoria  Porcentagem
0                 CBC   Sudeste        60.20
1    NÃO SABE A MARCA   Sudeste        14.43
2              MORIGI   Sudeste        16.42
3              Outros   Sudeste         9.45
4              BUFALO   Sudeste        12.44
5                LYON   Sudeste         3.98
6           MARCONDES   Sudeste        10.45
7               EAGLE   Sudeste         4.98
8             FEDERAL   Sudeste         3.48
9           PRECISION   Sudeste         2.49

=== MODALI.PROJÉTIL ===
✅ Modali.Projétil OK

                      Motivo de utilizar o projétil  Porcentagem
0                              Qualidade/Desempenho        32.50
1                             Preço/Custo-Benefício        25.50
2                        Confiança/Costume/Parceria        23.50
3    Disponibilidade/Logística/Facilidade de compra        23.00
4                         Disponibilidade/Logística        11.25
5                              Não Sabe/Sem Opinião         9.75
6                        Mais conhecida / Tradição          3.25
7                                    Mais conhecida         2.50
8                       Tradição / Tempo no mercado         0.75
9                    É a única fabricante do modelo         3.00

=== RECOM.PROJÉTEIS ===
Colunas em Recom.Projéteis: ['Motivo', 'BULLETS (%)', 'CBC (%)', 'MORIGI (%)', 'MARCONDES (%)', 'LYON (%)', 'BUFALO (%)']
✅ Recom.Projéteis OK (matriz)

                                             Motivo    Categoria  Porcentagem
0                              Qualidade/Desempenho  BULLETS (%)          0.0
1                        Confiança/Costume/Parceria  BULLETS (%)          0.0
2                             Preço/Custo-Benefício  BULLETS (%)          0.0
3    Disponibilidade/Logística/Facilidade de compra  BULLETS (%)        100.0
4                         Disponibilidade/Logística  BULLETS (%)          0.0
5                              Não Sabe/Sem Opinião  BULLETS (%)          0.0
6                        Mais conhecida | Tradição   BULLETS (%)          0.0
7                    É a única fabricante do modelo  BULLETS (%)          0.0
8             Peso mais preciso / Melhor balanceado  BULLETS (%)          0.0
9                                    Amigos indicam  BULLETS (%)          0.0

=== TIPOS PROJÉTEIS ===
✅ Tipos Projéteis OK

  Qual tipo de projétil que hoje você sente falta ou não encontra facilmente?
0                                                NaN
1                                          Projéteis
2                                       Não informou
3                                               .308
4                                         IMPORTADOS
5                                   9MM | 9 MM PLANA
6                                                .40
7                                         CANTO VIVO
8                                          PONTA OCA
9                                               7.62

=== TESTARNOVO ===
✅ TestarNovo OK

  Em quais condições você consideraria testar um novo projétil de uma marca que ainda não conhece?
0                                                NaN
1                                           Condição
2                  Se o preço fosse mais competitivo
3                                   Amostra gratuita
4                     Após testes práticos em treino
5    Se o desempenho fosse comprovado por testes ...
6    Com recomendação técnica (instrutor, clube o...
7    Se estivesse disponível na loja/clube que co...
8                    Não costumo testar marcas novas
9                              Produto regulamentado

=== MOTIVAÇÃONOVO ===
✅ MotivaçãoNovo OK

  O que mais lhe motivaria a testar um novo projétil?
0                                                NaN
1                                           Condição
2                                 Amostras gratuitas
3                                  Preço promocional
4                                Testes comparativos
5                                Prova de desempenho
6                                  Indicação técnica
7                                Conteúdo no Youtube
8                                 Demanda do cliente
9                                       Não informou

=== CONFIA.MARCAS ===
✅ Confia.Marcas OK

  Que argumentos uma nova marca de projéteis precisa apresentar para ganhar sua confiança?
0                                                NaN
1                                          Argumento
2                     Acabamento/Preservação Da Arma
3     Algum diferencial em relação à marca utilizada
4                  Baixa emissão de gases e resíduos
5                                Confiança/Segurança
6                     Confiança/Segurança no disparo
7                   Controle obrigatório do SisGcorp
8                                   Design homogêneo
9            Disponibilidade/Facilidade de aquisição

=== CONFIA.PERFIL ===
✅ Confia.Perfil OK

,Argumento,Usuário Final (%),Gestor de Clube (%),Gestor de Loja de Armaria (%)
0,Confiança / Segurança no disparo,47.0,41,43
1,Preço/Custo-Benefício,35.0,36,37
2,Precisão || Desempenho do disparo,24.0,32,17
3,Testes de provas | Laudos,17.5,16,30
4,Padronização de peso | Medida,12.5,14,10
5,Preservação da arma,7.5,12,12
6,Facilidade de aquisição,11.0,9,6
7,Não sabe,3.5,8,7
8,Diferencial em relação à marca utilizada,2.0,3,3
9,Recomendação de pessoas relevantes no setor,1.0,4,4

=== ERROS MERCADO ===
✅ Erros Mercado OK

  Na sua opinião, quais erros marcas novas costumam cometer nesse mercado?
0                                                NaN
1                                             Motivo
2  Qualidade/Falta padronização peso / pintura / ...
3  Falta divulgação e marketing das vantagens do ...
4                                           Não sabe
5                                         Preço alto
6      Prazo de entrega ruim / Pouca disponibilidade
7  Colocam o poduto no mercado sem testar a segur...
8      Preço inicial próximo de marcas já conhecidas
9     Não fazem workshops e demonstrações nos clubes

=== REDE ===
✅ Rede OK

  Onde você busca informação confiável sobre produtos de tiro?
0                                                NaN
1                                              Canal
2                             Internet/Midia/Digital
3                                  Atiradores/Amigos
4                     Autoridade/Instrutores/Atletas
5                                             Clubes
6                                  Fabricantes/Lojas
7                         Testes/Experiência própria
8                   Informativos Técnicos/Documentos
9                                       Não informou

🚀 BLOCO FINAL PROCESSADO COM SUCESSO!